### PR TITLE
Fix maven configuration

### PR DESCRIPTION
**Pull request by slandelle**
* Make root the parent module
* introduce a core-only profile, used typically for releases
* fix scm configuration

### CODE REVIEW

**Comment by tdunning** [comment]
Very helpful!

So with this, I assume that the normal release:prepare and similar steps would receive -Pcore-only?

I presume that I could build a 3.3 parent pom by applying the profile and scm changes to the old parent/pom.xml so that I could redo the release and retain only the parent pom in the release process. Does that make sense to you?

**Comment by slandelle** [comment]
Yes, this should work:

1. `mvn release:prepare release:perform -Pcore-only` directy in root dir
2. connect to Sonatype OSS, and remove core module files from the staging repository before closing and releasing it

**Comment by tdunning** [comment]
OK. THAT was harder than it should have been.

1) Java 12 versus old javadoc versus maven bug

     Had to specific a language level for the javadoc plugin

2) ./parent and ./core project structure doesn't work right with combo of github and maven so release:prepare failed. This bug has been known for nearly 10 years. See https://issues.apache.org/jira/browse/MRELEASE-767 for some history.

     Had to put bogus scm connection to point to origin rather than the full git URL to fix the problem with release:prepare

3) Fix for item (2) breaks release:perform. That required `-DlocalCheckout` to avoid any reference to the github repo during the perform step.

4) the documentation for maven scm URLs on the maven site is wrong as to the form of github URLs.

5) Various items had to be copied from the core pom to the parent pom to satisfy sonatypes release checks.

But ... it worked!

See https://github.com/tdunning/t-digest-example for an example of a free-standing project that uses the new version.

Now I just have to clean up the mess for the mainline development.

**Comment by slandelle** [comment]
1. Sorry, I really didn't test that :( I compile all my projects with Java 8 because of ByteBuffer binary compatibility breakage.
2. 3. 4. 5. Actually, I suspect your issues come from the fact I didn't force/upgrade all the plugins versions so you're still using the old buggy versions from the time maven 3.0 was released and default versions were set. I'll provide a PR for upgrading/setting the plugins versions.

**Comment by tdunning** [comment]
Actually, I moved to a much more recent version of the release plugin. No
change.

You can't really see the extra experiments that I did, but I did grid
search in options to try to understand things. I think I tried nearly a
hundred alternatives.

Still, all advice is welcome, especially regarding the newer, more standard
structure.  Frankly, in my down moods, I think I might well just revert to
using three separate projects and tell people to use maven install.

**Comment by slandelle** [comment]
Well, I'm 100% sure I could fix things for you if you were willing to (temporarily) make me a committer (so I can create the tag and the commits) and a publisher on maven central on the `com.tdunning` groupId. I can perfectly understand if you're not willing to go this way.

Anyway, I'm going to provide an extra PR with all the upgrades. I've done this kind of things many times, eg https://github.com/AsyncHttpClient/async-http-client

**Comment by tdunning** [comment]
I am happy to take your updates and test them for you. Or have you test
them..

But I would like to hear what structure you are headed for before that.

**Comment by slandelle** [comment]
> But I would like to hear what structure you are headed for before that.

I don't suggest any more structure changes. The ones you've merged are plenty enough IMHO.
I'm just suggesting forcing plugins versions instead of using defaults (that were never updated since maven 3.0 ages ago, because that would be a breaking change).

**Comment by tdunning** [comment]
Well, I would like to move to a structure that you suggested with the parent at the root. The parallel parent is a mess and seems to be outside the vision that maven has (otherwise, I wouldn't have seen so many ancient bugs).

But even that is up for debate. Should there even be a unifying pom?

And how should serialization packages be handled? My guess is that they should be parallel to core and released as separate artifacts to avoid dependencies on the core package. Your input would be valuable.

**Comment by slandelle** [comment]
> Well, I would like to move to a structure that you suggested with the parent at the root.

Sorry, I don't get it. This is what this PR you've already merged does, see https://github.com/tdunning/t-digest/pull/173/files#diff-8d04401f1cc51365fe3e32f019cd720135ba920a1a7da7f19e9c9208478701fcR27

> And how should serialization packages be handled? 

What are you referring to?

**Comment by tdunning** [comment]
Sorry about the confusion. The t-digest-3.3-repair branch still has the old
structure. I don't want that to survive.

Regarding serialization, it is desirable to have serialization for digests
using, say, Avro, Arrow, Kryo, JSON, protobuf and other frameworks. But
each of these introduces dependencies that I want to avoid for the core
t-digest package. Also, users of Arrow should not need to have Kryo or
protobuf dependencies.

Thus, my thought that releasing separate serialization artifacts would be
good. To me, this is the strongest argument right now for multiple modules.

**Comment by slandelle** [comment]
> Sorry about the confusion. The t-digest-3.3-repair branch still has the old
structure. I don't want that to survive.

Well, the `main` branch looks pretty good to me. BTW, I had fixed your scm issue: https://github.com/tdunning/t-digest/commit/8630c2b678ae5d2c055ee26bea6cf0af79c55fa6#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R11-R12

> Thus, my thought that releasing separate serialization artifacts would be
good. To me, this is the strongest argument right now for multiple modules.

Yes, each one of those should should be a module. Way cleaner than a huge module with lots of optional dependencies (or worse, not flagged as optional).

**Comment by tdunning** [comment]
On Mon, Jun 14, 2021 at 9:55 AM Stephane Landelle ***@***.***>
wrote:

> Sorry about the confusion. The t-digest-3.3-repair branch still has the old
> structure. I don't want that to survive.
>
> Well, the main branch looks pretty good to me. BTW, I had fixed your scm
> issue: 8630c2b
> #diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R11-R12
> <https://github.com/tdunning/t-digest/commit/8630c2b678ae5d2c055ee26bea6cf0af79c55fa6#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R11-R12>
>

"fixed" in the sense of made correct. Unfortunately, this interacted with
the bugs I hit in the maven release plugin so I had to make it "wrong" to
get it to work.

I prefer your path. Make it right and make the structure work with what
maven likes.

**Pull request merged**
